### ISSUE TITLE
マッパソン全体のスライド作成

### ISSUE THREAD

**Issue by Ayako-T** [furuhashilab/youthmappers4agu#65]

**Comment by ibuki76** [comment]
@Maxputa 司会担当の柴山です。全体の流れを把握しておきたいので、大まかに決まったらslackかgoogle driveかこちらに共有していただきたいです！

**Comment by Maxputa** [comment]
くにはるが5日に先生と当日の流れを決めるみたいだから、もうちょい待ってて

**Comment by Maxputa** [comment]
@ibuki76 くにはるが5日に先生と当日の流れを決めるみたいだから、もうちょい待ってて

**Comment by ibuki76** [comment]
かしこまりましたー！

**Comment by Maxputa** [comment]
https://docs.google.com/presentation/d/1hSBfZJLE4OT1Fh8K1Fb9D0BYhs4sKgySlPp6Ci2HBPo/edit?usp=sharing

**Comment by Maxputa** [comment]
これが
